/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatientTriageDemoRouteImport } from './routes/patient-triage-demo'
import { Route as NpiPhysicianLookupRouteImport } from './routes/npi-physician-lookup'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const PatientTriageDemoRoute = PatientTriageDemoRouteImport.update({
  id: '/patient-triage-demo',
  path: '/patient-triage-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const NpiPhysicianLookupRoute = NpiPhysicianLookupRouteImport.update({
  id: '/npi-physician-lookup',
  path: '/npi-physician-lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/npi-physician-lookup': typeof NpiPhysicianLookupRoute
  '/patient-triage-demo': typeof PatientTriageDemoRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/npi-physician-lookup': typeof NpiPhysicianLookupRoute
  '/patient-triage-demo': typeof PatientTriageDemoRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/npi-physician-lookup': typeof NpiPhysicianLookupRoute
  '/patient-triage-demo': typeof PatientTriageDemoRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/npi-physician-lookup'
    | '/patient-triage-demo'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/npi-physician-lookup' | '/patient-triage-demo' | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/npi-physician-lookup'
    | '/patient-triage-demo'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NpiPhysicianLookupRoute: typeof NpiPhysicianLookupRoute
  PatientTriageDemoRoute: typeof PatientTriageDemoRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patient-triage-demo': {
      id: '/patient-triage-demo'
      path: '/patient-triage-demo'
      fullPath: '/patient-triage-demo'
      preLoaderRoute: typeof PatientTriageDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/npi-physician-lookup': {
      id: '/npi-physician-lookup'
      path: '/npi-physician-lookup'
      fullPath: '/npi-physician-lookup'
      preLoaderRoute: typeof NpiPhysicianLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NpiPhysicianLookupRoute: NpiPhysicianLookupRoute,
  PatientTriageDemoRoute: PatientTriageDemoRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
